base_url = "https://oselotl.com"
title = "oselotl"
theme = "DeepThought"
compile_sass = true
generate_feed = true

[extra]
navbar_items = [
 { code = "en", nav_items = [
   { url = "$BASE_URL/", name = "Home" },
   { url = "$BASE_URL/posts", name = "Posts" },
   { url = "$BASE_URL/about", name = "About" },
 ]},
]

# Adding other required DeepThought theme settings
favicon = "/static/icon.png"
copyright = "© 2025 oselotl"