base_url = "https://oselotl.com"
title = "oselotl"
description = "Your site description"
theme = "duckquill"

# Required settings for duckquill
compile_sass = true
build_search_index = true
generate_feed = true

[markdown]
highlight_code = true

[extra]
author = "Your Name"