name: Zola Deploy

on: push
  # push:
  #   branches:
  #     - main  # or master, depending on your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Update theme submodule
        run: |
          git submodule update --init --force --recursive
          git submodule update --remote --merge
      
      - name: Build and Deploy
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # BUILD_DIR: .
          # BUILD_ONLY: false
          # BUILD_FLAGS: --force
